### ISSUE TITLE
Error while trying to create two consumers at the same time

### ISSUE THREAD

**Issue by yanivbh1** [Memphis-OS/memphis.js#26] opened 2022-05-12 09:59 UTC
```
const memphis = require("memphis-dev");
const { sendConfirmation } = require('../controllers/emailController')
const { logger } = require('./loggerService')
const MEMPHIS_HOST = process.env.MEMPHIS_HOST || 'localhost'; // create MQ connection string using environment variable
const MEMPHIS_USERNAME = process.env.MEMPHIS_USERNAME || 'fastmart';
const MEMPHIS_TOKEN = process.env.MEMPHIS_TOKEN || 'memphis';

/**
 * Connect to Memphis and consumer orders
 */
const memphisConnect = async () => {
    try {
        logger.info(`Memphis - trying to connect`)
        await memphis.connect({
            host: MEMPHIS_HOST,
            username: MEMPHIS_USERNAME,
            connectionToken: MEMPHIS_TOKEN
        });
        logger.info(`Memphis - connection established`)
        
        ordersStation_consumer = await memphis.consumer({
            stationName: "orders",
            consumerName: "email_service",
        });
        logger.info(`ordersStation_consumer created`)

        notificationsStation_consumer = await memphis.consumer({
            stationName: "notifications",
            consumerName: "email_service",
        });
        logger.info(`notificationsStation_consumer created`)

        ordersStation_consumer.on("message", order => {
            // processing
            logger.info("New order received")
            logger.info(order.getData().toString())
            sendConfirmation(order);
        });

        notificationsStation_consumer.on("message", notification => {
            // processing
            logger.info("New notification requirement")
            logger.info(notification.getData().toString())
            sendNotificationViaEmail(notification);
        });
    }
    catch (ex) {
        logger.log('fatal',`Memphis - ${ex}`);
        memphis.close();
        process.exit();
    }
}

module.exports = {
    memphisConnect: memphisConnect
}

```

**Comment by idanasulinmemphis** [comment] 2022-05-15 14:37
This issue caused by a bug located in the control plane so please update your memphis deployment and it will be fixed

**Closed by idanasulinmemphis** 2022-05-15 14:37 UTC
Labels: bug
